### PR TITLE
Incorrect calculation of validator custody requirement

### LINKED ISSUE #205: Incorrect calculation of validator custody requirement
Hi! I was looking through CL client implementations of validator custody and noticed a possible issue with custody requirement calculation in the Teku implementation:

The implementation of [calculateCustodyGroupCount](https://github.com/Nashatyrev/teku/blob/b2a4784f035f8f176fb495b471629a12e47f7181/ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java#L168) multiplies validator bases by `VALIDATOR_CUSTODY_REQUIREMENT`.

In the [spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/fulu/validator.md#validator-custody) a node with validators should custody at least `VALIDATOR_CUSTODY_REQUIREMENT` columns, but only 1 additional column for each validator basis

### PR DESCRIPTION
**Pull request by jeroost**
## PR Description
Update custody group requirement to latests Fulu specs

## Fixed Issue(s)
Fixes #205

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigFuluImpl.java [hunk 1]
```diff
@@ -145,6 +148,11 @@ public SpecMilestone getMilestone() {
     return SpecMilestone.FULU;
   }
 
+  @Override
+  public UInt64 getBalancePerAdditionalCustodyGroup() {
+    return balancePerAdditionalCustodyGroup;
+  }
+
```
Comment (zilm13) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigFuluImpl.java:155]: `validatorCustodyRequirement`,
        `samplesPerSlot`,
        `balancePerAdditionalCustodyGroup`

        are missed from `equals` and `hashCode`
       we forgot about it before but now I've noticed

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java [hunk 2]
```diff
@@ -162,13 +162,17 @@ public List<UInt64> getCustodyGroups(final UInt256 nodeId, final int custodyGrou
...
-  public UInt64 calculateCustodyGroupCount(
-      final int defaultCustodyGroupCount, final long baseValidatorsNumber) {
-    final UInt64 validatorCustodyGroupCount =
-        UInt64.valueOf(baseValidatorsNumber).times(specConfigFulu.getValidatorCustodyRequirement());
-    return validatorCustodyGroupCount
-        .max(defaultCustodyGroupCount)
-        .min(specConfigFulu.getNumberOfCustodyGroups());
+  public int calculateCustodyGroupCount(
+      final int defaultCustodyGroupCount, final UInt64 totalNodeBalance) {
+    if (totalNodeBalance.isZero()) {
```
Comment (zilm13) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java]: this is not needed, zero divided by something is zero

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java [hunk 3]
```diff
@@ -162,13 +162,17 @@ public List<UInt64> getCustodyGroups(final UInt256 nodeId, final int custodyGrou
...
 
-  public UInt64 calculateCustodyGroupCount(
-      final int defaultCustodyGroupCount, final long baseValidatorsNumber) {
-    final UInt64 validatorCustodyGroupCount =
-        UInt64.valueOf(baseValidatorsNumber).times(specConfigFulu.getValidatorCustodyRequirement());
-    return validatorCustodyGroupCount
-        .max(defaultCustodyGroupCount)
-        .min(specConfigFulu.getNumberOfCustodyGroups());
+  public int calculateCustodyGroupCount(
+      final int defaultCustodyGroupCount, final UInt64 totalNodeBalance) {
```
Comment (zilm13) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java]: We need to somehow highlight that it should be `effective` balance. Maybe `totalEffectiveValidatorsBalance` or `effectiveValidatorsBalanceSum`? What do you think?

File: ethereum/spec/src/test/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFuluTest.java [hunk 4]
```diff
@@ -237,6 +240,34 @@ public void emptyInclusionProofFromRealNetwork_shouldFailValidation() {
         .isFalse();
   }
 
+  @Test
+  public void testCalculateCustodyGroupCount() {
```
Comment (zilm13) [inline ethereum/spec/src/test/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFuluTest.java]: Refactor to `ParameterizedTest`, see `getExtendedSampleCountReturnsCorrectValues` above for an example. Also I'd input total balance in ETH for readability and multiply it by billion in the body of the test.

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java (hunk 3 above)
Comment (zilm13) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java]: Also let's rename and refactor to be closer to the spec: let it be 2 methods: `getCustodyRequirement(int, UImt64)` { if (Uint64 == ZERO} return int else `getValidatorCustodyRequirement(Uint64)`

**Review by zilm13 — COMMENTED** [review]
LGTM just few nits

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java (hunk 2 above)
Comment (jeroost) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java]: It was needed. For the case where no effective balance -> non-validating node so we should return default custody group count (4) which is not the same as minimal validator group count (8).
But agree with the comment below to make two methods, getCustodyRequirement and getValidatorCustodyRequirement to make it more similar to spec

Comment (zilm13) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/fulu/helpers/MiscHelpersFulu.java]: Sorry, missed it, now got it!

**Review by zilm13 — APPROVED** [review]
LGTM
