### PR TITLE
Remove joins in DataColumnSidecars

### LINKED ISSUE #66: Teku DAS misses slots
Teku lags to produce blocks in time, see orphaned statistics: https://dora.peerdas-devnet-1.ethpandaops.io/slots/filtered?f&d=1+2+3+4+5+6+7+8+9+10+11&f.missing=1&f.orphaned=2&c=50

Clearly visible something that looks like "CPU leaking" and comb on epoch transition. During hours with low CPU usage there are no issues.
There are a lot of errors like this in logs, which is expected when we miss onSlot ticks:
```
2024-06-26 18:38:18.002 ERROR - [31mValidator   *** Failed to produce attestation  Slot: 8833 Validator: a56a236[0m
java.lang.IllegalArgumentException: Cannot create attestation for future slot. Requested 8833 but current slot is 8832
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createAttestationData(ValidatorApiHandler.java:398) ~[teku-beacon-validator-develop.jar:UNKNOWN+g3768eca]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:80) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:125) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:116) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```
[thread_dumps.zip](https://github.com/user-attachments/files/16036755/thread_dumps.zip)

### PR DESCRIPTION
**Pull request by zilm13**
Hope it will fix #66

### CODE REVIEW

**Review by Nashatyrev — APPROVED** [review]
LGTM

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImpl.java [hunk 1]
```diff
@@ -214,104 +223,97 @@ public void onSlot(UInt64 slot) {
...
+            slotCustodies ->
+                slotCustodies.stream()
+                    .filter(SlotCustody::isIncomplete)
+                    .findFirst()
+                    .ifPresentOrElse(
+                        custody ->
+                            db.setFirstIncompleteSlot(custody.slot())
+                                .ifExceptionGetsHereRaiseABug(),
+                        () ->
+                            db.setFirstIncompleteSlot(slotCustodies.getLast().slot())
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImpl.java:243]: `List.getLast()` is in Java 21+
