### PR TITLE
Fix missing Gossip subnet subscription on startup

### LINKED ISSUE #166: Not subscribing to Gossip subnets occasionally
Sometime a client for some reasons doesn't subscribe to subnets (including columns, attestations, etc).
image

### PR DESCRIPTION
**Pull request by Nashatyrev**
## PR Description

`GossipForkManager` has two different sources of `isHeadOptimistic`flag:  
- `RecentChainData.isChainHeadOptimistic()` when starting up
- `onOptimisticHeadChanged()` to update the flag 

There are possible cases (e.g. #166) when the value differs in those two sources. Thus subnet subscriptions (which are to be activated when `isHeadOptimistic` becomes `false`) may not be activated.

This PR initializes the flag with `RecentChainData.isChainHeadOptimistic()` value and then relies on `onOptimisticHeadChanged()` notifications only 

## Fixed Issue(s)

Fix #166

### CODE REVIEW

**Review by tbenr — APPROVED** [review]
LGTM

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/forks/GossipForkManager.java [hunk 1]
```diff
@@ -300,11 +302,9 @@ private boolean isActive(final GossipForkSubscriptions subscriptions) {
     return activeSubscriptions.contains(subscriptions);
   }
 
-  private void startSubscriptions(final GossipForkSubscriptions subscription) {
+  private synchronized void startSubscriptions(final GossipForkSubscriptions subscription) {
```
Comment (zilm13) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/forks/GossipForkManager.java]: all calls are from `configureGossipForEpoch` which is already synchronized and looks sync. Is synchronizatiion needed here too?

**Review by zilm13 — APPROVED** [review]
LGTM
