### PR TITLE
Fix reconstruction of missing DataColumnSidecars on gossip

### LINKED ISSUE #184: Reconstruction is not working
After some changes recontrsuction looks broken. It works when syncing from the scratch, but it fails to reconstruct when some columns are missed on gossip and not provided in time.

### PR DESCRIPTION
**Pull request by zilm13**
fixes #184 
Introduces column reconstruction from gossip.

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/retriever/SimpleSidecarRetriever.java [hunk 1]
```diff
@@ -120,6 +120,19 @@ public void flush() {
...
 
+  @Override
+  public void onNewValidatedSidecar(final DataColumnSidecar sidecar) {
+    final DataColumnSlotAndIdentifier dataColumnSlotAndIdentifier =
+        DataColumnSlotAndIdentifier.fromDataColumn(sidecar);
+    final Optional<RetrieveRequest> maybeRequest =
+        pendingRequests.entrySet().stream()
+            .filter(request -> request.getKey().equals(dataColumnSlotAndIdentifier))
+            .filter(request -> !request.getValue().result.isDone())
+            .findFirst()
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/retriever/SimpleSidecarRetriever.java]: May be just `forEach()` here?

Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/retriever/SimpleSidecarRetriever.java]: could we have two for the same index?

Comment (Nashatyrev) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/retriever/SimpleSidecarRetriever.java]: Probably not, but that could potentially change.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarByRootCustody.java [hunk 2]
```diff
@@ -15,11 +15,13 @@
...
 import java.util.Optional;
 import tech.pegasys.teku.infrastructure.async.SafeFuture;
+import tech.pegasys.teku.infrastructure.async.stream.AsyncStream;
 import tech.pegasys.teku.spec.datastructures.blobs.versions.fulu.DataColumnSidecar;
+import tech.pegasys.teku.spec.datastructures.blocks.SlotAndBlockRoot;
 import tech.pegasys.teku.spec.datastructures.networking.libp2p.rpc.DataColumnIdentifier;
 import tech.pegasys.teku.spec.datastructures.util.DataColumnSlotAndIdentifier;
 
-public interface DataColumnSidecarByRootCustody extends DataColumnSidecarCustody {
+public interface DataColumnSidecarByRootCustody extends UpdatableDataColumnSidecarCustody {
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarByRootCustody.java]: Maybe we should merge interfaces  UpdatableDataColumnSidecarCustody to DataColumnSidecarCustody just to make it simpler?

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImpl.java [hunk 3]
```diff
@@ -244,4 +245,12 @@ public AsyncStream<DataColumnSlotAndIdentifier> retrieveMissingColumns() {
     return retrievePotentiallyIncompleteSlotCustodies(currentSlot.minusMinZero(gossipWaitSlots))
         .flatMap(SlotCustody::streamIncompleteColumns);
   }
+
+  @Override
+  public AsyncStream<DataColumnSlotAndIdentifier> retrieveMissingColumns(
+      final SlotAndBlockRoot blockId) {
+    return retrievePotentiallyIncompleteSlotCustodies(blockId.getSlot())
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImpl.java]: Looks suboptimal. Maybe better use `retrieveSlotCustody()` here?

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java [hunk 4]
```diff
@@ -0,0 +1,290 @@
...
+
+              final List<SlotAndBlockRoot> ids =
+                  recoveryTasks.keySet().stream()
+                      .filter(key -> key.getSlot().equals(slot))
+                      .toList();
+              ids.stream()
+                  .map(recoveryTasks::get)
+                  .forEach(
+                      task -> {
+                        task.timeouted().set(true);
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: nit: Maybe better 'timedOut()'?

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java [hunk 5]
```diff
@@ -0,0 +1,290 @@
...
+    asyncRunner
+        .runAfterDelay(
+            () -> {
+              LOG.debug("Check if recovery needed for slot: {}", slot);
+
+              final List<SlotAndBlockRoot> ids =
+                  recoveryTasks.keySet().stream()
+                      .filter(key -> key.getSlot().equals(slot))
+                      .toList();
+              ids.stream()
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: nit: can we do it with a single map entries stream to make it more clear ?

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java [hunk 6]
```diff
@@ -0,0 +1,290 @@
...
+      final DataColumnSlotAndIdentifier identifier) {
+    if (recoveryTasks.containsKey(identifier.getSlotAndBlockRoot())) {
+      final RecoveryTask existing = recoveryTasks.get(identifier.getSlotAndBlockRoot());
+      existing.existing().add(identifier);
+      maybeStartRecovery(existing);
+    } else {
+      RecoveryTask recoveryTask =
+          new RecoveryTask(
+              new AtomicReference<>(null),
+              new HashSet<>(),
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: nit:
```java
new HashSet<>(List.of(identifier)), 
```

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/UpdatableDataColumnSidecarCustody.java [hunk 7]
```diff
@@ -16,11 +16,15 @@
...
 import tech.pegasys.teku.spec.datastructures.util.DataColumnSlotAndIdentifier;
 
 public interface UpdatableDataColumnSidecarCustody extends DataColumnSidecarCustody {
 
   SafeFuture<Void> onNewValidatedDataColumnSidecar(DataColumnSidecar dataColumnSidecar);
 
   AsyncStream<DataColumnSlotAndIdentifier> retrieveMissingColumns();
+
+  /** Includes non-canonical sidecar identificators */
+  AsyncStream<DataColumnSlotAndIdentifier> retrieveMissingColumns(SlotAndBlockRoot blockId);
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/UpdatableDataColumnSidecarCustody.java]: Sorry, didn't find where this method is used

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java [hunk 8]
```diff
@@ -0,0 +1,290 @@
...
+  }
+
+  private boolean isActiveSuperNode(final UInt64 slot) {
+    return isSuperNode
+        && spec.atSlot(slot).getMilestone().isGreaterThanOrEqualTo(SpecMilestone.FULU);
+  }
+
+  private record RecoveryTask(
+      AtomicReference<BeaconBlock> block,
+      Set<DataColumnSlotAndIdentifier> existing,
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: nit: maybe more descriptive field name for better code reading: `existingColumnIds` e.g.?

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java (hunk 4 above)
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: nit: as an option instead of `timedOut` field we may just have class wide `timedOutSlot` field, increase it here and then consider all tasks with slots below as time out

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java [hunk 9]
```diff
@@ -0,0 +1,290 @@
...
+      final BeaconBlock block, final SafeFuture<List<DataColumnSidecar>> list) {
+    LOG.info("Starting data columns sidecars recovery for block: {}", block.getSlotAndBlockRoot());
+
+    list.thenPeek(
+            sidecars -> {
+              LOG.debug(
+                  "Recovery for block: {}. DatacolumnSidecars found: {}",
+                  block.getSlotAndBlockRoot(),
+                  sidecars.size());
+              final Map<UInt64, DataColumnSidecar> existingSidecarsByColIdx = new HashMap<>();
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: nit: We need just a set of indexes here:  
```java
              Set<UInt64> existingSidecarIndexes =
                  sidecars.stream().map(DataColumnSidecar::getIndex).collect(Collectors.toSet());
```

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/UpdatableDataColumnSidecarCustody.java (hunk 7 above)
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/UpdatableDataColumnSidecarCustody.java]: Good catch, it was previous version, I don't need it anymore and all other changes in implementations

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImpl.java (hunk 3 above)
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImpl.java]: ....and it's gone!

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java (hunk 9 above)
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: Nice catch!

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java (hunk 4 above)
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: I want recovery start at certain seconds into a slot

Comment (Nashatyrev) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: It would, if you update `timedOutSlot` and then call `maybeStartRecovery()`. 
But anyway the current version also works, just a bit of excessive data

Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: So I could have 64+ data columns already but don't want to fire recovery if it's just 1 second into slot

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java [hunk 10]
```diff
@@ -0,0 +1,281 @@
...
+            .map(Optional::get)
+            .toList();
+    initiateRecovery(task.block().get(), list);
+  }
+
+  private void initiateRecovery(
+      final BeaconBlock block, final SafeFuture<List<DataColumnSidecar>> list) {
+    LOG.info("Starting data columns sidecars recovery for block: {}", block.getSlotAndBlockRoot());
+
+    list.thenPeek(
```
Comment (Nashatyrev) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: nit: `thenAccept()` looks as more appropriate method (the result would be the same though :)

**Review by Nashatyrev — APPROVED** [review]
LGTM

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java (hunk 4 above)
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarRecoveringCustodyImpl.java]: I could do only this as an improvement https://github.com/Nashatyrev/teku/pull/191/commits/d2447057d147e810740262f3e82936189e5f056b
